### ISSUE TITLE
Suggestion: split the tests in separate files

### ISSUE THREAD

**Issue by Lucas-C** [DavidFirth/pdfjam#10]
My understanding is that currently `tests/run.sh` contain all the tests.

I suggest to split them into separate files to ease their maintenance,
and allow to easily execute a single test.

Here is an approach I used on another CLI tool:
https://github.com/plainas/tq/blob/master/tqtest.sh

I'm willing to submit a PR in that direction if you agree with that plan ! :)

**Comment by DavidFirth** [comment]
Thanks, Lucas.  That does seem a good suggestion.  I would be happy to get that pull request.
