### ISSUE TITLE
I want to change the page size of a particular page in a pdf

### ISSUE THREAD

**Issue by sant527** [DavidFirth/pdfjam#17]
I have a pdf file with all pages of different page sizes.

I have attached the pdf file test2_cropped_cropped.pdf

Now in this file i want to change the page size of only the 2nd page and keep the remaining pages as they are.

How can we achieve this.

Ys
Simha Rupa DAs
[test2_cropped_cropped.pdf](https://github.com/DavidFirth/pdfjam/files/3896371/test2_cropped_cropped.pdf)

**Comment by DavidFirth** [comment]
No help available here, sorry.
