### ISSUE TITLE
Empty page ({}) not empty but is another named page

### ISSUE THREAD

**Issue by schoettl** [DavidFirth/pdfjam#18]
```
$ pdfjam --version
2.08
$ pdfjam -o result.pdf test.pdf '{},1'
```

Problem:
- The first page in result.pdf is not empty ({}) but is the first page of
  test.pdf
- The second page in result.pdf is also the first page of test.pdf (correct)

**Comment by DavidFirth** [comment]
Thanks for reporting.  Can you please run again with --no-tidy and then get the .tex file (from the temporary directory that is made) to show me here?

**Comment by schoettl** [comment]
```
\batchmode
\documentclass[a4paper,]{article}
\usepackage[utf8]{inputenc}
\usepackage{pdfpages}

\begin{document}
\includepdfmerge[]{/var/tmp/pdfjam-CSCJ9j/source-1.pdf,{},1}
\end{document}
```

**Comment by schoettl** [comment]
OK, it's not your bug :) but thanks for helping to debug it. I mailed the maintainer of the pdfpages LaTeX package. The package documentanion was updated at end of November. The `{}` still should insert empty pages, but they seem to introduced a bug.

**Comment by schoettl** [comment]
So, with the current version of pdfpages from CTAN it should work again:

https://ctan.org/ctan-ann/id/mailman.2543.1576766197.2586.ctan-ann@ctan.org

But I don't know when the update will be distributed to operating system packages.

**Comment by schoettl** [comment]
I close this.

I thought `pdfpages` in the texlive distribution and waited months for an update. But it is not. I have to install it manually. On Arch Linux, it's on AUR, but integrity checks fail.

**Comment by schoettl** [comment]
I just read your README, it says, that `pdfpages` *should* be in texlive.

But I just checked on Arch, according to https://wiki.archlinux.org/index.php/TeX_Live#Installation

> To determine which CTAN packages are included in each texlive- package, look up the files /var/lib/texmf/arch/installedpkgs/<package>_<revnr>.pkgs.

It's not there, I installed `texlive-most`. I don't understand this.

**Comment by DavidFirth** [comment]
I don't understand it either -- sorry.

**Comment by cmsigler** [comment]
@schoettl 

This bug fix is finally "downstreamed" in Arch as of March 30 and April 2, 2020.  You'll need packages currently in testing:

texlive-bin 2020.54586-1
texlive-core 2020.54593-1

You'll also need poppler 0.87.0-1.  After these upgrades if WFM.  Hope this helps :^)

Clemmitt Sigler

**Comment by DavidFirth** [comment]
Thanks for this, @schoettl -- much appreciated.

**Comment by schoettl** [comment]
Cool, thanks @cmsigler for the info and thank you @DavidFirth for this package :)
