### ISSUE TITLE
Support heterogenous landscape/portrait PDFs 

### ISSUE THREAD

**Issue by palladius** [DavidFirth/pdfjam#28]
Hi - first your script ROCKS! So good! 
I'm trying to put all my tax statements in one, 99% of them are vertical and a few are portrait. 
If I merge together homogeneous PDFs, all good, but if I merge both styles the final PDF becomes portrait for all pages.
Now I have a Music sheet PDF somewhere where pages are some verticals and some horizontal - I thought it was horrible but now it's what I would desire. 
Is there a way to set the flags to get a single PDFs with some pages in vertical and some in horizontal? I've tried these flags with no luck:

* --rotateoversize false
* --no-landscape 
* --fitpaper 'true'

**Comment by DavidFirth** [comment]
Current pdfjam does not do what you want, sorry.  That is a consequence of deliberate design changes made at version 2.00.

You could perhaps try using one of the earlier versions (prior to 2.00) where this sort of mixing of output pages was possible.  See "older releases" in the README page.  Alternatively I think there might be other software that does this, too.
