### ISSUE TITLE
is thiis sollution can be done?

### ISSUE THREAD

**Issue by Davidzhu001** [DavidFirth/pdfjam#36]
![image](https://user-images.githubusercontent.com/9436230/99218196-c71dad80-2814-11eb-8444-411bc04d4288.png)

**Comment by DavidFirth** [comment]
Not really a pdfjam issue, I think, so I am closing this.  @Davidzhu001 Most likely you need to read the documentation for pdfpages: see the link that appears in `pdfjam --help`. 

Possibly the option `--nup 3x2` is the sort of thing you want to use.
