### ISSUE TITLE
Preserve PDF annotations by using pax?

### ISSUE THREAD

**Issue by DavidFirth** [DavidFirth/pdfjam#6]
Suggestion received as below.  I have not looked into it.  If someone wanted to investigate, implement, check everything and make a minimal patch for `pdfjam`, then it could be a good addition I think.

----- Forwarded message from Alexander  ----- 

Date: Fri, 27 Jan 2017 14:24:18 +0100
From: Alexander 
To: David Firth 
Subject: PDFjam suggestion: keep annotations using pax

Hi David,

thanks a ton for the incredibly useful PDFjam tool.

I have a small suggestion for it: as you state yourself, a "potential drawback of pdfjam and other scripts based upon it is that any hyperlinks in the source PDF are lost."  Heiko Oberdiek wrote an (experimental, but AFAICS quite reliable) combination of an annotation extractor and a corresponding LaTeX package to reintegrate them: pax [1]. 

Its usage is fairly simple if properly installed: before the run of pdflatex on the temporary file containing the pdfpages commands, run   pdfannotextractor --install  # only on first run
  for infile in source-*.pdf; do 
    pdfannotextractor $infile
  done
and add an
  \include{pax}
after
  \include{pdfpages}
in the temporary texfile.  Afterwards, compile (twice?) and enjoy preserved hyperlinks.  Unfortunately, bookmarks are still lost as of yet, but at least the links and destinations are there. Also, pax is aware of geometry changes, so anchor positions are adjusted if pages are rescaled. 

The above approach works out-of-the-box on my Arch Linux installation with current TeXLive.  And it seems to be reasonably easy to integrate, so even if pax is not easily available for everyone, it might be worth to have a look. 

Thanks again for your tool!
Alexander

[1]: https://www.ctan.org/pkg/pax

----- End forwarded message -----

**Comment by DavidFirth** [comment]
It looks as though _pax_ is still described by its author as "experimental".  So I will not implement this, for now at least.

**Comment by kde35** [comment]
> Hi sorry for bumping this. I landed here when googling for "Preserve PDF annotations pdfjam", and I would just like to link this issue to issue [#57](https://github.com/pdfjam/pdfjam/issues/57) because in issue [#57](https://github.com/pdfjam/pdfjam/issues/57), a partial workaround was described.

Unfortunately the command `gs -dSAFER -dBATCH -dNOPAUSE -dNOCACHE -sDEVICE=pdfwrite -dPreserveAnnots=false -sOutputFile=out.pdf in.pdf` removes hyperlinks
